[programs.localnet]
<<<<<<< feature/oracle
open_parametric = "BXxqMY3f9y7dzvoQWJjhX95GMEyuRjD61kgfgherhSX7"
=======
open_parametric = "3dBd52Do2ZBbaMboLyuVZSJTupAFKGoorEydQ6MkfiPL"
>>>>>>> main

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn test"
